--UNITY_TEST_TEAM has read access on "UNITY_TEST_DB"
USE ROLE SECURITYADMIN;

GRANT OWNERSHIP ON TABLE UNITY_TEST_DB.UNITY_STAGING.STG_PLATFORM_PROJECT_EVENT  TO ROLE UNITY_TEST_MIGRATION_TEAM COPY CURRENT GRANTS;
